language: node_js

node_js:
  - 12

services:
  - docker  # Start Docker service

before_install:
  # Print Docker version for logging
  - docker --version

script:
  # Build the Docker images for each service
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-api-reverse-proxy ./udagram-api-reverse-proxy

  # Tag each image with the appropriate Docker Hub repository and version
  - docker tag udagram-api-feed lava500/udagram-api-feed:v1
  - docker tag udagram-api-user lava500/udagram-api-user:v1
  - docker tag udagram-api-frontend lava500/udagram-api-frontend:v1
  - docker tag udagram-api-reverse-proxy lava500/udagram-api-reverse-proxy:v1

after_success:
  # Docker login using credentials stored in Travis CI environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  # Push the tagged Docker images to Docker Hub
  - docker push lava500/udagram-api-feed:v1
  - docker push lava500/udagram-api-user:v1
  - docker push lava500/udagram-api-frontend:v1
  - docker push lava500/udagram-api-reverse-proxy:v1
