language: node_js

node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker --version # print the version for logging
  - docker-compose version

script:
  - docker --version # Print Docker version for logging
  - export IMAGE="lava500/udagram-frontend:v1" # Set image name with a proper tag
  - docker build -t $IMAGE . # Build the image
  - docker tag $IMAGE lava500/udagram-frontend # Tag the image


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lava500/udagram-api-user:v1a
  - docker push lava500/udagram-api-feed:v1a
  - docker push lava500/udagram-frontend:local
  - docker push lava500/reverseproxy:v1a
